"""
Install userSetup.py to Maya Scripts Directory

This creates a userSetup.py file that automatically adds user site-packages
to Maya's Python path on startup, fixing the "No module named 'plyfile'" issue.

Run this ONCE in Maya:
    exec(open(r'C:\Users\thero\OneDrive\Documents\GitHub\flash3d\maya_plugin\install_userSetup.py').read())
"""

import os
import maya.cmds as cmds

# Get Maya scripts directory
maya_scripts_dir = cmds.internalVar(userScriptDir=True)
userSetup_path = os.path.join(maya_scripts_dir, 'userSetup.py')

print("\n" + "="*70)
print("SplatCraft - Install userSetup.py")
print("="*70)

# userSetup.py content
userSetup_content = '''"""
Maya User Setup - Auto-generated by SplatCraft
This file is automatically executed when Maya starts.
"""

import sys
import site

# Add user site-packages to Python path
# This allows Maya to find packages installed with pip
user_site = site.getusersitepackages()
if user_site not in sys.path:
    sys.path.insert(0, user_site)
    print(f"[userSetup] Added user site-packages: {user_site}")

print("[userSetup] SplatCraft environment initialized")
'''

# Check if userSetup.py already exists
if os.path.exists(userSetup_path):
    print(f"\nFound existing userSetup.py at:")
    print(f"  {userSetup_path}")
    print("\nReading existing file...")

    with open(userSetup_path, 'r') as f:
        existing_content = f.read()

    # Check if our code is already there
    if 'site.getusersitepackages()' in existing_content:
        print("\n✓ User site-packages already configured in userSetup.py!")
        print("  No changes needed.")
    else:
        print("\n⚠ userSetup.py exists but doesn't have our configuration.")
        print("\nOptions:")
        print("  1. Manually add this to your userSetup.py:")
        print("\n" + userSetup_content)
        print("\n  2. Or backup your current file and let me create a new one.")
        print("\nTo backup and replace, run:")
        print("  # In Maya Python:")
        print("  import shutil")
        print(f"  shutil.copy(r'{userSetup_path}', r'{userSetup_path}.backup')")
        print(f"  # Then run this script again")
else:
    print(f"\nCreating new userSetup.py at:")
    print(f"  {userSetup_path}")

    try:
        with open(userSetup_path, 'w') as f:
            f.write(userSetup_content)

        print("\n✓ userSetup.py created successfully!")
        print("\n⚠ IMPORTANT: Restart Maya for changes to take effect!")
        print("\nWhat this does:")
        print("  - Automatically adds user site-packages to Python path on Maya startup")
        print("  - Fixes 'No module named plyfile/OpenGL' errors")
        print("  - Runs every time Maya starts")

    except Exception as e:
        print(f"\n✗ Error creating userSetup.py: {e}")

print("="*70 + "\n")
